name: Test Unitaire

on:
  push:
    branches: [ keep_white_space ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - use: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install


   