name: Test Unitaire

on:
  push:
    branches: [keep_white_space]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        working-directory: Keep_White_Space
        run: npm install
      - name: Run tests
        working-directory: Keep_White_Space
        run: npm test
