name: Test Unitaire

on:
  push:
    branches:
    - '*'
    - '*/*'
    
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        working-directory: Keep_White_Space
        run: npm install
      - name: Run tests
        working-directory: Keep_White_Space
        run: npm test
